---
title: "Undifferentiated Cluster Analysis"
author: "Brennan McDonald"
date: "2024-04-03"
output: html_document
---

```{r}
library(tidyverse)
library(Seurat)
```

```{r}
CreateSeuratObject(load(
  file = "6-60hr\ Integrated\ UMAP/HE_6-60hpf_integrated-SCT6k_195dim.Rda", 
                        verbose = T))
```

####################
Export UMAPs for figure 4
####################

```{r}
library(scCustomize)

# Export as 6x8 for figure 4
Cluster_Highlight_Plot(he.integrated,
                       cluster_name = "Set Aside",
                       pt.size = 0.3,
                       highlight_color = "lightpink") +
  theme(legend.position = "none")
```



```{r}
# Subset the integrated object for cluster 40, which corresponds to the putative stem cluster
stem <- subset(he.integrated, seurat_clusters == 40)
```

```{r}
DimPlot(stem, reduction = "umap", group.by = "group", label = TRUE, repel = TRUE)
```

```{r}
stem_sub <- FindNeighbors(stem, dims = 1:195)
stem_sub <- FindClusters(stem_sub, resolution = 0.5)
stem_sub <- RunUMAP(stem_sub, dims = 1:195)

DimPlot(stem_sub, reduction = "umap", group.by = "group", label = TRUE, repel = TRUE)
DimPlot(stem_sub, reduction = "umap", label = TRUE)

stem_sub.markers <- FindAllMarkers(stem_sub, only.pos = T, min.pct = 0.25, 
                                   logfc.threshold = 0.25)

```


```{r}
# Extract cluster 40 markers from the differentially expressed marker file for the broader integrated object

he.markers <- read_csv("6-60hr\ Integrated\ UMAP/HE_6-60hr_cluster-markers.csv")

stem.markers <- he.markers %>% 
  filter(cluster == 40)
```

```{r}
# Number of cells in stem cluster over time

stem@meta.data %>% 
  group_by(Stage) %>% 
  summarize(count = n()) %>% 
  add_row(Stage = "60hpf", count = 0) %>% 
  mutate(time = c(6, 9, 12, 16, 20, 24, 30, 36, 42, 48, 54, 60)) %>% 
  ggplot(mapping = aes(x = time, y = count)) + 
  geom_line(color = "darkblue", linewidth = 0.8) +
  geom_point() + 
  scale_x_continuous(breaks = c(6, 9, 12, 16, 20, 24, 30, 36, 42, 48, 54, 60),
                     limits = c(6, 60)) +
  labs(y = "Number of Cells in Stem Cluster", x = "Hours Post Fertilization") + 
  theme_bw()
```



```{r}
# Subset the integrated object for cluster 40, which corresponds to the putative stem cluster
stem <- subset(he.integrated, seurat_clusters == 40)
```

```{r}
DimPlot(stem, reduction = "umap", group.by = "group", label = TRUE, repel = TRUE)
```

```{r}
stem_sub <- FindNeighbors(stem, dims = 1:195)
stem_sub <- FindClusters(stem_sub, resolution = 0.5)
stem_sub <- RunUMAP(stem_sub, dims = 1:195)

DimPlot(stem_sub, reduction = "umap", group.by = "group", label = TRUE, repel = TRUE)
DimPlot(stem_sub, reduction = "umap", label = TRUE)

stem_sub.markers <- FindAllMarkers(stem_sub, only.pos = T, min.pct = 0.25, 
                                   logfc.threshold = 0.25)

```


```{r}
# Extract cluster 40 markers from the differentially expressed marker file for the broader integrated object

he.markers <- read_csv("6-60hr\ Integrated\ UMAP/HE_6-60hr_cluster-markers.csv")

stem.markers <- he.markers %>% 
  filter(cluster == 40)
```

```{r}
# Number of cells in stem cluster over time

stem@meta.data %>% 
  group_by(Stage) %>% 
  summarize(count = n()) %>% 
  add_row(Stage = "60hpf", count = 0) %>% 
  mutate(time = c(6, 9, 12, 16, 20, 24, 30, 36, 42, 48, 54, 60)) %>% 
  ggplot(mapping = aes(x = time, y = count)) + 
  geom_line(color = "darkblue", linewidth = 0.8) +
  geom_point() + 
  scale_x_continuous(breaks = c(6, 9, 12, 16, 20, 24, 30, 36, 42, 48, 54, 60),
                     limits = c(6, 60)) +
  labs(y = "Number of Cells in Stem Cluster", x = "Hours Post Fertilization") + 
  theme_bw()
```


# GO analysis of marker genes for set aside cluster

##########################################################################
**Activate the ./conda/clusterProfiler conda environment for this script**
k#########################################################################

```{r}
library(dplyr)
library(readr)
library(stringr)
library(org.Herythrogramma.eg.db)
library(clusterProfiler)
```

```{r}
s_markers <- FindMarkers(he.integrated, ident.1 = "Set Aside", 
                         only.pos = T, 
                         min.pct = 0.25, 
                         logfc.threshold = 0.25)

s_markers <- s_markers %>% 
  filter(p_val_adj < 0.05) %>% 
  slice_max(n = 500, order_by = avg_log2FC)

#write.csv(s_markers, 
#          "6-60hr\ Integrated\ UMAP/stem-cluster-analysis/set-aide_full-markers.csv",
#          row.names = T)
```

```{r}
s_markers <- read_csv("6-60hr\ Integrated\ UMAP/stem-cluster-analysis/set-aide_full-markers.csv")
```

```{r}
library(clusterProfiler)
library(org.Herythrogramma.eg.db)

hery_ids <- str_split_i(s_markers$gene, ":", 1)
hery_ids <- str_replace_all(hery_ids, "HER-", "HER_")

setaside_go <- enrichGO(gene = hery_ids,
                  OrgDb = org.Herythrogramma.eg.db,
                  keyType = "GID",
                  ont = "BP",
                  pvalueCutoff = 0.05,
                  pAdjustMethod = "BH",
                  qvalueCutoff = 0.2)

View(setaside_go@result)

enrichplot::dotplot(setaside_go, showCategory = 10) +
  scale_fill_gradient(low = "blue", high = "red")

###################
# Use this for figure 4
# Export as 5x6
barplot(setaside_go, showCategory = 10) +
  scale_fill_gradient(low = "blue", high = "lightblue")
###################


simp_go <- simplify(setaside_go, cutoff = 0.5)
enrichplot::dotplot(simp_go, showCategory = 10)
barplot(simp_go)
heatplot(simp_go)
cnetplot(simp_go, node_label = "category")
```


# Make new WoT heatmap

```{r}
library(ComplexHeatmap)
library(circlize)

ttable <- read.csv("6-60hr\ Integrated\ UMAP/stem-cluster-analysis/Wot_transition-table_6-60hr-values.csv", row.names = 1)

col_fun = colorRamp2(breaks = c(0,0.2), colors = c("white", "red"))

Heatmap(matrix = ttable,
        cluster_rows = F,
        cell_fun = function(j, i, x, y, width, height, fill) {
          grid.text(sprintf("%.3f", ttable[i,j]), x, y, gp = gpar(fontsize = 8))},
        width = ncol(ttable)*unit(10, "mm"),
        height = nrow(ttable)*unit(10, "mm"),
        show_column_names = F, 
        col = col_fun)
```


# Coexpression plots for germline marker genes

```{r}
umap_coords <- as_tibble(Embeddings(he.integrated, reduction = "umap"))
umap_coords$Cell <- rownames(Embeddings(he.integrated, reduction = "umap"))
```

```{r}
coexp_plot <- function(coords, low_exp, high_exp) {
  coords1 <- coords %>% 
    mutate(Expression = case_when(Cell %in% low_exp ~ "Low Coexpression",
                                  .default = "No Coexpression")) %>% 
    mutate(Expression = if_else(Cell %in% high_exp, "High Coexpression", Expression))
    
  coords1$Expression <- factor(coords1$Expression, 
         levels = c("No Coexpression", "Low Coexpression", "High Coexpression"))
  
  coords1 %>%   
    arrange(Expression) %>% 
    ggplot(mapping = aes(x = UMAP_1, y = UMAP_2, 
                         color = Expression)) +
    geom_point(size = 0.3) +
    scale_color_discrete(type = c("gray", "lightgreen", "darkgreen")) +
    labs(color = "Coexpression Level") +
    theme_classic() +
    theme(legend.position = "none")
}
```

```{r}
nanos_vasa05 <- WhichCells(he.integrated, 
                           expression = `HER-1713.t1:Sp-Nanos2` >= 0.5 &
                             `HER-6048.t1:Sp-Vasa` >= 0.5)
nanos_vasa1 <- WhichCells(he.integrated, 
                           expression = `HER-1713.t1:Sp-Nanos2` >= 1 &
                             `HER-6048.t1:Sp-Vasa` >= 1)

coexp_plot(coords = umap_coords,
           low_exp = nanos_vasa05,
           high_exp = nanos_vasa1)
```

```{r}
seawi_vasa05 <- WhichCells(he.integrated, 
                           expression = `HER-1053.t1:Sp-Seawi-1` >= 0.5 &
                             `HER-6048.t1:Sp-Vasa` >= 0.5)
seawi_vasa1 <- WhichCells(he.integrated, 
                           expression = `HER-1053.t1:Sp-Seawi-1` >= 1 &
                             `HER-6048.t1:Sp-Vasa` >= 1)

coexp_plot(coords = umap_coords,
           low_exp = seawi_vasa05,
           high_exp = seawi_vasa1)
```

```{r}
nanos_seawi05 <- WhichCells(he.integrated, 
                           expression = `HER-1713.t1:Sp-Nanos2` >= 0.5 &
                             `HER-1053.t1:Sp-Seawi-1` >= 0.5)
nanos_seawi1 <- WhichCells(he.integrated, 
                           expression = `HER-1713.t1:Sp-Nanos2` >= 1 &
                             `HER-1053.t1:Sp-Seawi-1` >= 1)

coexp_plot(coords = umap_coords,
           low_exp = nanos_seawi05,
           high_exp = nanos_seawi1)
```

```{r}
# triple expression
nanos_seawi_vasa05 <- WhichCells(he.integrated, 
                           expression = `HER-1713.t1:Sp-Nanos2` >= 0.5 &
                             `HER-1053.t1:Sp-Seawi-1` >= 0.5 &
                             `HER-6048.t1:Sp-Vasa` >= 0.5)
nanos_seawi_vasa1 <- WhichCells(he.integrated, 
                           expression = `HER-1713.t1:Sp-Nanos2` >= 1 &
                             `HER-1053.t1:Sp-Seawi-1` >= 1 &
                             `HER-6048.t1:Sp-Vasa` >= 1)

# Export as 6x8 for figure 4
coexp_plot(coords = umap_coords,
           low_exp = nanos_seawi_vasa05,
           high_exp = nanos_seawi_vasa1)
```


# Cell type dendrogram

```{r}
library(ape)

he.integrated <- BuildClusterTree(he.integrated,
                                  verbose = T)

tree <- Tool(object = he.integrated, slot = 'BuildClusterTree')

plot.phylo(tree, 
           direction = "downwards",
           type = "phylogram",
           use.edge.length = T,
           cex = 0.5)
```
